# Generated by Django 4.1.2 on 2022-10-09 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "authenticate",
            "0004_remove_user_user_user_email_user_lat_user_long_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="User",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
