# Generated by Django 4.1.2 on 2022-10-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0006_alter_test_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test", name="dateTime", field=models.DateTimeField(),
        ),
    ]
