# Generated by Django 4.1.2 on 2022-10-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0007_alter_test_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapy",
            name="User_IDmed",
            field=models.IntegerField(null=True),
        ),
    ]
