# Generated by Django 4.1.2 on 2022-10-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0008_therapy_user_idmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapy_list",
            name="Dosage",
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
