# Generated by Django 4.1.2 on 2022-10-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0009_therapy_list_dosage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="lat",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="long",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="userID",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
