# Generated by Django 4.1.2 on 2022-10-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0010_alter_user_lat_alter_user_long_alter_user_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapy_list",
            name="Medicine_IDmedicine",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.medicine",
            ),
            preserve_default=False,
        ),
    ]
