# Generated by Django 4.1.2 on 2022-10-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0012_alter_therapy_user_idpatient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapy",
            name="TherapyList_IDtherapylist",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.therapy_list",
            ),
            preserve_default=False,
        ),
    ]
