# Generated by Django 4.1.2 on 2022-10-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0015_alter_test_session_test_idtest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="Test_Session_IDtest_session",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.test_session",
            ),
            preserve_default=False,
        ),
    ]
