# Generated by Django 4.1.2 on 2022-10-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0019_alter_user_role_idrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="authenticate.organization",
            ),
            preserve_default=False,
        ),
    ]
