# Generated by Django 4.1.2 on 2022-10-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0021_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="dateAdded",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
