# Generated by Django 4.1.2 on 2022-10-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0022_alter_comments_dateadded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="user",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
