# Generated by Django 4.1.2 on 2022-10-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0023_alter_comments_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="data_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
